"""
Domain Models module.
Encapsulates all structured data contracts and Pydantic schemas.
"""

from datetime import datetime
from typing import Any
from pydantic import BaseModel, Field


class RetrievedChunk(BaseModel):
    """Pydantic model representing a single document chunk retrieved from pgvector."""

    text: str = Field(..., description="Text content of the retrieved chunk.")
    filename: str = Field(..., description="Original filename the chunk belongs to.")
    score: float = Field(..., description="Cosine similarity score (0.0 to 1.0).")
    chunk_index: int = Field(default=0, description="Sequential index of the chunk in the document.")


class RetrievedContext(BaseModel):
    """Pydantic model representing assembled context for LLM generation."""

    formatted_prompt: str = Field(
        ...,
        description="Formatted context string with clear delimiters to protect against prompt injection.",
    )
    sources: list[str] = Field(
        default_factory=list,
        description="Unique list of source filenames cited in the retrieved context.",
    )
    chunks: list[RetrievedChunk] = Field(
        default_factory=list,
        description="Raw retrieved chunk objects.",
    )


class IngestionResult(BaseModel):
    """Pydantic model summarizing the outcome of a document ingestion pipeline."""

    doc_id: str = Field(..., description="UUID of the ingested document.")
    filename: str = Field(..., description="Name of the file.")
    chunk_count: int = Field(default=0, description="Number of embedding chunks created and stored.")
    message: str = Field(..., description="Human-readable status summary.")
    already_exists: bool = Field(default=False, description="True if the file hash already existed in workspace.")


class AgentToolEvent(BaseModel):
    """Structured record of a tool execution event performed by the agent."""

    tool_name: str = Field(..., description="Name of the tool executed.")
    tool_args: dict[str, Any] = Field(default_factory=dict, description="Arguments passed to the tool.")
    tool_output: str = Field(default="", description="Output message generated by the tool.")
    status: str = Field(default="complete", description="Execution status: 'complete' or 'error'.")


class AgentResponse(BaseModel):
    """Structured response returned by the Document Assistant Agent."""

    answer: str = Field(..., description="The final synthesized answer generated by the agent.")
    sources: list[str] = Field(default_factory=list, description="Document filenames cited from retrieved context.")
    tool_events: list[AgentToolEvent] = Field(
        default_factory=list, description="List of tools executed during reasoning."
    )


class UserSession(BaseModel):
    """Represents an authenticated user profile in session state."""

    id: str = Field(..., description="User unique ID from Neon Auth.")
    email: str = Field(..., description="User email address.")


class Workspace(BaseModel):
    """Represents a tenant workspace."""

    id: str = Field(..., description="Workspace UUID.")
    user_id: str = Field(..., description="Owning user ID.")
    name: str = Field(..., description="Display name of the workspace.")
    created_at: datetime | str | None = Field(default=None, description="Timestamp created.")


class WorkspaceTask(BaseModel):
    """Represents an action item recorded in workspace_tasks."""

    id: str = Field(..., description="Task UUID.")
    workspace_id: str = Field(..., description="Workspace ID boundary.")
    title: str = Field(..., description="Task title / action item description.")
    priority: str = Field(default="medium", description="Priority level: high, medium, or low.")
    created_at: datetime | str | None = Field(default=None, description="Creation timestamp.")


class ToolLog(BaseModel):
    """Represents an audit entry recorded in tool_logs."""

    id: str = Field(..., description="Log entry UUID.")
    workspace_id: str = Field(..., description="Workspace ID boundary.")
    tool_name: str = Field(..., description="Name of tool.")
    status: str = Field(..., description="SUCCESS or FAILED.")
    arguments: dict[str, Any] = Field(default_factory=dict, description="Arguments passed.")
    error_message: str | None = Field(default=None, description="Error details if failed.")
    created_at: datetime | str | None = Field(default=None, description="Timestamp.")
